### ISSUE TITLE
There is no "tune_dirichlet_nn.py" in the repo

### ISSUE THREAD

**Issue by JunwenBai** [dirichletcal/experiments_dnn#1]
In the readme, there is calibration commands including tune_dirichlet_nn.py. But I cannot find them in the repo.

**Comment by markus93** [comment]
Hey! Thanks for pointing out the issue. There was a typo in the ReadMe, instead of "tune_dirichlet_nn.py" there should be "tune_cal_odir.py".

Let me know if there are any more questions! :)
