### ISSUE TITLE
Project licence

### ISSUE THREAD

**Issue by darnox** [dirichletcal/experiments_dnn#2]
Hi!
I find your implementation of `Dirichlet_NN` very useful for a project I am working on! The only problem is that this repository doesn't have any license file attached, and I wouldn't want to violate your copyright. 
Would you mind adding an appropriate license that would allow the community to use your code? 

PS I'm aware of [dirichlet_python](https://github.com/dirichletcal/dirichlet_python) package that is distributed under MIT license but it doesn't contain NN implementation

**Comment by markus93** [comment]
Hey!

Thanks for pointing that out! Now, the license is added to this repository. :)

All the best,
Markus

**Comment by darnox** [comment]
Thanks!
